-- liquibase formatted sql

-- changeset lafonina:1
CREATE TABLE notification_task(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
chat_id BIGINT NOT NULL,
message TEXT NOT NULL,
notification_date_time TIMESTAMP NOT NULL
);